name: test
on: [pull_request]
jobs:
  job1: 
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: First
      uses: SuneetBansal/test-repo@master
      with:
        version2: "SUNEETSUNEETSUNEETSUNEET"
    - name : Second
      uses: sshnaidm/gpt-code-review-action@v1.0
      with:
        openai-key: "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"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    -  name: First
       uses: actions/checkout@v2
    -  name: Second
       run: "Get-ChildItem Env:"
    
